// Generated by gencpp from file multiwii/MSPRawMessage.msg
// DO NOT EDIT!


#ifndef MULTIWII_MESSAGE_MSPRAWMESSAGE_H
#define MULTIWII_MESSAGE_MSPRAWMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multiwii
{
template <class ContainerAllocator>
struct MSPRawMessage_
{
  typedef MSPRawMessage_<ContainerAllocator> Type;

  MSPRawMessage_()
    : id(0)
    , data()  {
    }
  MSPRawMessage_(const ContainerAllocator& _alloc)
    : id(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::multiwii::MSPRawMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multiwii::MSPRawMessage_<ContainerAllocator> const> ConstPtr;

}; // struct MSPRawMessage_

typedef ::multiwii::MSPRawMessage_<std::allocator<void> > MSPRawMessage;

typedef boost::shared_ptr< ::multiwii::MSPRawMessage > MSPRawMessagePtr;
typedef boost::shared_ptr< ::multiwii::MSPRawMessage const> MSPRawMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multiwii::MSPRawMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multiwii::MSPRawMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multiwii::MSPRawMessage_<ContainerAllocator1> & lhs, const ::multiwii::MSPRawMessage_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multiwii::MSPRawMessage_<ContainerAllocator1> & lhs, const ::multiwii::MSPRawMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multiwii

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multiwii::MSPRawMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiwii::MSPRawMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiwii::MSPRawMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiwii::MSPRawMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiwii::MSPRawMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiwii::MSPRawMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multiwii::MSPRawMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd42210221b2280d84f6ed0e3b881126";
  }

  static const char* value(const ::multiwii::MSPRawMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd42210221b2280dULL;
  static const uint64_t static_value2 = 0x84f6ed0e3b881126ULL;
};

template<class ContainerAllocator>
struct DataType< ::multiwii::MSPRawMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multiwii/MSPRawMessage";
  }

  static const char* value(const ::multiwii::MSPRawMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multiwii::MSPRawMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint8[] data\n"
;
  }

  static const char* value(const ::multiwii::MSPRawMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multiwii::MSPRawMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MSPRawMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multiwii::MSPRawMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multiwii::MSPRawMessage_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIWII_MESSAGE_MSPRAWMESSAGE_H
