// Generated by gencpp from file multiwii/ReceiveMSPRawMessageResponse.msg
// DO NOT EDIT!


#ifndef MULTIWII_MESSAGE_RECEIVEMSPRAWMESSAGERESPONSE_H
#define MULTIWII_MESSAGE_RECEIVEMSPRAWMESSAGERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <multiwii/MSPRawMessage.h>

namespace multiwii
{
template <class ContainerAllocator>
struct ReceiveMSPRawMessageResponse_
{
  typedef ReceiveMSPRawMessageResponse_<ContainerAllocator> Type;

  ReceiveMSPRawMessageResponse_()
    : msg()  {
    }
  ReceiveMSPRawMessageResponse_(const ContainerAllocator& _alloc)
    : msg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::multiwii::MSPRawMessage_<ContainerAllocator>  _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReceiveMSPRawMessageResponse_

typedef ::multiwii::ReceiveMSPRawMessageResponse_<std::allocator<void> > ReceiveMSPRawMessageResponse;

typedef boost::shared_ptr< ::multiwii::ReceiveMSPRawMessageResponse > ReceiveMSPRawMessageResponsePtr;
typedef boost::shared_ptr< ::multiwii::ReceiveMSPRawMessageResponse const> ReceiveMSPRawMessageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator1> & lhs, const ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator2> & rhs)
{
  return lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator1> & lhs, const ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multiwii

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e01cb4af5047b763cb98e1ac7628835";
  }

  static const char* value(const ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e01cb4af5047b76ULL;
  static const uint64_t static_value2 = 0x3cb98e1ac7628835ULL;
};

template<class ContainerAllocator>
struct DataType< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multiwii/ReceiveMSPRawMessageResponse";
  }

  static const char* value(const ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MSPRawMessage msg\n"
"\n"
"\n"
"================================================================================\n"
"MSG: multiwii/MSPRawMessage\n"
"uint8 id\n"
"uint8[] data\n"
;
  }

  static const char* value(const ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReceiveMSPRawMessageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multiwii::ReceiveMSPRawMessageResponse_<ContainerAllocator>& v)
  {
    s << indent << "msg: ";
    s << std::endl;
    Printer< ::multiwii::MSPRawMessage_<ContainerAllocator> >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIWII_MESSAGE_RECEIVEMSPRAWMESSAGERESPONSE_H
