// Generated by gencpp from file multiwii/ReceiveMSPRawMessageRequest.msg
// DO NOT EDIT!


#ifndef MULTIWII_MESSAGE_RECEIVEMSPRAWMESSAGEREQUEST_H
#define MULTIWII_MESSAGE_RECEIVEMSPRAWMESSAGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multiwii
{
template <class ContainerAllocator>
struct ReceiveMSPRawMessageRequest_
{
  typedef ReceiveMSPRawMessageRequest_<ContainerAllocator> Type;

  ReceiveMSPRawMessageRequest_()
    : id(0)  {
    }
  ReceiveMSPRawMessageRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReceiveMSPRawMessageRequest_

typedef ::multiwii::ReceiveMSPRawMessageRequest_<std::allocator<void> > ReceiveMSPRawMessageRequest;

typedef boost::shared_ptr< ::multiwii::ReceiveMSPRawMessageRequest > ReceiveMSPRawMessageRequestPtr;
typedef boost::shared_ptr< ::multiwii::ReceiveMSPRawMessageRequest const> ReceiveMSPRawMessageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator1> & lhs, const ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator1> & lhs, const ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multiwii

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "541b98e964705918fa8eb206b65347b3";
  }

  static const char* value(const ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x541b98e964705918ULL;
  static const uint64_t static_value2 = 0xfa8eb206b65347b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multiwii/ReceiveMSPRawMessageRequest";
  }

  static const char* value(const ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
;
  }

  static const char* value(const ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReceiveMSPRawMessageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multiwii::ReceiveMSPRawMessageRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTIWII_MESSAGE_RECEIVEMSPRAWMESSAGEREQUEST_H
