// Generated by gencpp from file multiwii/ReceiveMSPRawMessage.msg
// DO NOT EDIT!


#ifndef MULTIWII_MESSAGE_RECEIVEMSPRAWMESSAGE_H
#define MULTIWII_MESSAGE_RECEIVEMSPRAWMESSAGE_H

#include <ros/service_traits.h>


#include <multiwii/ReceiveMSPRawMessageRequest.h>
#include <multiwii/ReceiveMSPRawMessageResponse.h>


namespace multiwii
{

struct ReceiveMSPRawMessage
{

typedef ReceiveMSPRawMessageRequest Request;
typedef ReceiveMSPRawMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReceiveMSPRawMessage
} // namespace multiwii


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multiwii::ReceiveMSPRawMessage > {
  static const char* value()
  {
    return "df9470897e4eb0a05a5b4a1532d6a67f";
  }

  static const char* value(const ::multiwii::ReceiveMSPRawMessage&) { return value(); }
};

template<>
struct DataType< ::multiwii::ReceiveMSPRawMessage > {
  static const char* value()
  {
    return "multiwii/ReceiveMSPRawMessage";
  }

  static const char* value(const ::multiwii::ReceiveMSPRawMessage&) { return value(); }
};


// service_traits::MD5Sum< ::multiwii::ReceiveMSPRawMessageRequest> should match
// service_traits::MD5Sum< ::multiwii::ReceiveMSPRawMessage >
template<>
struct MD5Sum< ::multiwii::ReceiveMSPRawMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multiwii::ReceiveMSPRawMessage >::value();
  }
  static const char* value(const ::multiwii::ReceiveMSPRawMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multiwii::ReceiveMSPRawMessageRequest> should match
// service_traits::DataType< ::multiwii::ReceiveMSPRawMessage >
template<>
struct DataType< ::multiwii::ReceiveMSPRawMessageRequest>
{
  static const char* value()
  {
    return DataType< ::multiwii::ReceiveMSPRawMessage >::value();
  }
  static const char* value(const ::multiwii::ReceiveMSPRawMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multiwii::ReceiveMSPRawMessageResponse> should match
// service_traits::MD5Sum< ::multiwii::ReceiveMSPRawMessage >
template<>
struct MD5Sum< ::multiwii::ReceiveMSPRawMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multiwii::ReceiveMSPRawMessage >::value();
  }
  static const char* value(const ::multiwii::ReceiveMSPRawMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multiwii::ReceiveMSPRawMessageResponse> should match
// service_traits::DataType< ::multiwii::ReceiveMSPRawMessage >
template<>
struct DataType< ::multiwii::ReceiveMSPRawMessageResponse>
{
  static const char* value()
  {
    return DataType< ::multiwii::ReceiveMSPRawMessage >::value();
  }
  static const char* value(const ::multiwii::ReceiveMSPRawMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTIWII_MESSAGE_RECEIVEMSPRAWMESSAGE_H
