// Generated by gencpp from file multiwii/SendMSPRawMessage.msg
// DO NOT EDIT!


#ifndef MULTIWII_MESSAGE_SENDMSPRAWMESSAGE_H
#define MULTIWII_MESSAGE_SENDMSPRAWMESSAGE_H

#include <ros/service_traits.h>


#include <multiwii/SendMSPRawMessageRequest.h>
#include <multiwii/SendMSPRawMessageResponse.h>


namespace multiwii
{

struct SendMSPRawMessage
{

typedef SendMSPRawMessageRequest Request;
typedef SendMSPRawMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendMSPRawMessage
} // namespace multiwii


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multiwii::SendMSPRawMessage > {
  static const char* value()
  {
    return "0e01cb4af5047b763cb98e1ac7628835";
  }

  static const char* value(const ::multiwii::SendMSPRawMessage&) { return value(); }
};

template<>
struct DataType< ::multiwii::SendMSPRawMessage > {
  static const char* value()
  {
    return "multiwii/SendMSPRawMessage";
  }

  static const char* value(const ::multiwii::SendMSPRawMessage&) { return value(); }
};


// service_traits::MD5Sum< ::multiwii::SendMSPRawMessageRequest> should match
// service_traits::MD5Sum< ::multiwii::SendMSPRawMessage >
template<>
struct MD5Sum< ::multiwii::SendMSPRawMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multiwii::SendMSPRawMessage >::value();
  }
  static const char* value(const ::multiwii::SendMSPRawMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multiwii::SendMSPRawMessageRequest> should match
// service_traits::DataType< ::multiwii::SendMSPRawMessage >
template<>
struct DataType< ::multiwii::SendMSPRawMessageRequest>
{
  static const char* value()
  {
    return DataType< ::multiwii::SendMSPRawMessage >::value();
  }
  static const char* value(const ::multiwii::SendMSPRawMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multiwii::SendMSPRawMessageResponse> should match
// service_traits::MD5Sum< ::multiwii::SendMSPRawMessage >
template<>
struct MD5Sum< ::multiwii::SendMSPRawMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multiwii::SendMSPRawMessage >::value();
  }
  static const char* value(const ::multiwii::SendMSPRawMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multiwii::SendMSPRawMessageResponse> should match
// service_traits::DataType< ::multiwii::SendMSPRawMessage >
template<>
struct DataType< ::multiwii::SendMSPRawMessageResponse>
{
  static const char* value()
  {
    return DataType< ::multiwii::SendMSPRawMessage >::value();
  }
  static const char* value(const ::multiwii::SendMSPRawMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTIWII_MESSAGE_SENDMSPRAWMESSAGE_H
